controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

api_login_check:
  path: /api/login_check

api_login:
  path: /api/login
  controller: App\Controller\ApiController::apiLogin
  methods: ["POST"]
