controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

api_login_check:
  path: /api/login_check

api_login:
  path: /api/login
  controller: App\Controller\ApiController::apiLogin
  methods: ["POST"]

recette_create:
  path: "/recipe"
  controller: 'App\Controller\RecipeController::new'
  methods: ["POST"]

user_create:
  path: "/userCreate"
  controller: 'App\Controller\UserController::userCreate'
  methods: ["POST"]

get_allusers:
  path: /getAllUsers
  controller: App\Controller\UserController::getAllUsers
  methods: ["GET"]

make_admin:
  path: /makeAdmin
  controller: App\Controller\UserController::makeAdmin
  methods: ["PUT"]

delete_user:
  path: /userDelete
  controller: App\Controller\UserController::userDelete
  methods: ["DELETE"]
